overblog_graphql:
    errors_handler:
        debug: true
    definitions:
        schema:
            query: Query
            mutation: Mutation
        mappings:
            auto_discover: false
            types:
                - types: [graphql, yaml]
                  dir: "%kernel.project_dir%/config/graphql/types"
                  suffix: ~
                - type: yaml
                  dir: "%kernel.project_dir%/config/graphql/schema"
                  suffix: ~