version: '3'

volumes:
  jira_custom_dashboard-mysql_data:
    driver: local

networks:
  jira_custom_dashboard-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.72.0.0/24

services:
  apache:
    build: .
    networks:
      jira_custom_dashboard-network:
        aliases:
          - apache

  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      jira_custom_dashboard-network:
        aliases:
          - mysql
        ipv4_address: 172.72.0.101
    volumes:
      - jira_custom_dashboard-mysql_data:/var/lib/mysql
