version: '3'

volumes:
  jira_custom_dashboard-mysql_data:
    driver: local

networks:
  jira_custom_dashboard-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.72.0.0/24

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    networks:
      jira_custom_dashboard-network:
        aliases:
        - nginx

  php:
    build:
      context: .
      dockerfile: ./Dockerfile-php
    networks:
      jira_custom_dashboard-network:
        aliases:
          - php
          - backend-php

  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      jira_custom_dashboard-network:
        aliases:
          - mysql
        ipv4_address: 172.72.0.101
    volumes:
      - jira_custom_dashboard-mysql_data:/var/lib/mysql
