Query:
    type: object
    config:
        fields:
            sprintWidget:
                type: "SprintWidget"

            confidenceWidget:
                type: "ConfidenceWidget"

            AchievedSprintsWidget:
                type: "AchievedSprintsWidget!"
