Query:
    type: object
    config:
        fields:
            teamWidget:
                type: "[Team]"
                resolve: >
                    @=service("League\\Tactician\\CommandBus").handle(
                        newObject("Werkspot\\JiraDashboard\\TeamWidget\\Domain\\GetTeamsQuery")
                    )
            teamWidgetSprints:
                type: "[Sprint]"
                args:
                    teamId:
                        type: String!
                resolve: >
                    @=service("League\\Tactician\\CommandBus").handle(
                        newObject("Werkspot\\JiraDashboard\\TeamWidget\\Domain\\GetSprintsQuery", [
                            args["teamId"]
                       ])
                    )

            sprintWidget:
                type: Sprint
                args:
                    teamId:
                        type: String!
                resolve: >
                    @=service("League\\Tactician\\CommandBus").handle(
                        newObject("Werkspot\\JiraDashboard\\SprintWidget\\Domain\\GetActiveSprintByTeamQuery", [
                            args["teamId"]
                       ])
                    )

            confidenceWidget:
                type: "[Confidence]"
                args:
                    sprintId:
                        type: String!
                resolve: >
                    @=service("League\\Tactician\\CommandBus").handle(
                        newObject("Werkspot\\JiraDashboard\\ConfidenceWidget\\Domain\\GetConfidenceBySprintQuery", [
                            args["sprintId"]
                        ])
                    )

            burndownWidget:
                type: "[RemainingPoints]"
                args:
                    sprintId:
                        type: String!
                resolve: >
                    @=service("League\\Tactician\\CommandBus").handle(
                        newObject("Werkspot\\JiraDashboard\\BurndownWidget\\Domain\\GetRemainingPointsBySprintQuery", [
                            args["sprintId"]
                        ])
                    )

            achievedSprintsWidget:
                type: "AchievedSprints"
                args:
                    teamId:
                        type: String!
                resolve: >
                    @=service("League\\Tactician\\CommandBus").handle(
                        newObject("Werkspot\\JiraDashboard\\AchievedSprintsWidget\\Domain\\GetAchievedSprintsQuery", [
                            args["teamId"]
                        ])
                    )
