Query:
    type: object
    config:
        fields:
            sprintWidget:
                type: Sprint
                resolve: >
                    @=service("League\\Tactician\\CommandBus").handle(
                        newObject("Werkspot\\JiraDashboard\\SprintWidget\\Domain\\GetActiveSprintQuery")
                    )

            confidenceWidget:
                type: "[Confidence]"
                resolve: >
                    @=service("League\\Tactician\\CommandBus").handle(
                        newObject("Werkspot\\JiraDashboard\\ConfidenceWidget\\Domain\\GetConfidenceBySprintQuery")
                    )

            burndownWidget:
                type: "[RemainingPoints]"
                args:
                    sprintId:
                        type: String!
                resolve: >
                    @=service("League\\Tactician\\CommandBus").handle(
                        newObject("Werkspot\\JiraDashboard\\BurndownWidget\\Domain\\GetRemainingPointsBySprintQuery", [
                          args["sprintId"]
                        ])
                    )

            achievedSprintsWidget:
                type: "AchievedSprints"
                resolve: >
                    @=service("League\\Tactician\\CommandBus").handle(
                        newObject("Werkspot\\JiraDashboard\\AchievedSprintsWidget\\Domain\\GetAchievedSprintsQuery")
                    )
